import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ShadowContext from './context'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

console.log = () => {};
console.info = () => {};
console.warn = () => {};
console.error=()=>{};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black`}>
        <ShadowContext>
          {children}
        </ShadowContext>
        <Toaster />
      </body>
    </html>
  )
}
